import { Customer, Loan, Receipt, FixedDeposit } from '../types';

export const initialCustomers: Customer[] = [
  {
    id: 'CUST-001',
    name: 'thayba',
    phone: '+91 98401 23456',
    gender: 'Female',
    age: 32,
    occupation: 'Textile Boutique Owner',
    email: 'thayba@example.com',
    currentAddress: '14/2 Gandhi Road, T. Nagar, Chennai - 600017',
    permanentAddress: '14/2 Gandhi Road, T. Nagar, Chennai - 600017',
    idProof: 'Aadhaar Card',
    idNumber: 'XXXX-XXXX-8921',
    activeLoansCount: 1,
    totalBorrowed: 100000,
    status: 'VERIFIED',
    joinedDate: '15/01/2026'
  },
  {
    id: 'CUST-002',
    name: 'Rajan Sundaram',
    phone: '+91 98840 98765',
    gender: 'Male',
    age: 45,
    occupation: 'Civil Contractor',
    email: 'rajan.s@example.com',
    currentAddress: '88 North Mada Street, Mylapore, Chennai - 600004',
    permanentAddress: '88 North Mada Street, Mylapore, Chennai - 600004',
    idProof: 'PAN Card',
    idNumber: 'ABCDE1234F',
    activeLoansCount: 1,
    totalBorrowed: 150000,
    status: 'VERIFIED',
    joinedDate: '02/02/2026'
  },
  {
    id: 'CUST-003',
    name: 'Kavitha Murugan',
    phone: '+91 97910 54321',
    gender: 'Female',
    age: 38,
    occupation: 'School Teacher',
    email: 'kavitha.m@example.com',
    currentAddress: '22 Ring Road, Anna Nagar, Chennai - 600040',
    permanentAddress: '22 Ring Road, Anna Nagar, Chennai - 600040',
    idProof: 'Aadhaar Card',
    idNumber: 'XXXX-XXXX-4512',
    activeLoansCount: 1,
    totalBorrowed: 85000,
    status: 'VERIFIED',
    joinedDate: '10/03/2026'
  },
  {
    id: 'CUST-004',
    name: 'Arun Kumar',
    phone: '+91 94440 11223',
    gender: 'Male',
    age: 29,
    occupation: 'Software Engineer',
    email: 'arun.k@example.com',
    currentAddress: '5 Patel Street, Velachery, Chennai - 600042',
    permanentAddress: '5 Patel Street, Velachery, Chennai - 600042',
    idProof: 'Voter ID',
    idNumber: 'TN/02/123/456789',
    activeLoansCount: 0,
    totalBorrowed: 0,
    status: 'VERIFIED',
    joinedDate: '20/04/2026'
  }
];

export const initialLoans: Loan[] = [
  {
    id: 'L-01',
    receiptBillNo: 1,
    loanNo: 'GL-01',
    customerId: 'CUST-001',
    customerName: 'thayba',
    customerPhone: '+91 98401 23456',
    customerGender: 'Female',
    customerAge: 32,
    customerOccupation: 'Textile Boutique Owner',
    customerEmail: 'thayba@example.com',
    customerCurrentAddress: '14/2 Gandhi Road, T. Nagar, Chennai - 600017',
    customerPermanentAddress: '14/2 Gandhi Road, T. Nagar, Chennai - 600017',
    customerLocation: {
      captured: true,
      coordinates: '13.0418° N, 80.2341° E',
      mapsUrl: 'https://maps.google.com/?q=13.0418,80.2341',
      addressSummary: 'T. Nagar Branch Vicinity'
    },
    nominee: {
      hasNominee: true,
      name: 'Mohammed Ali',
      relationship: 'Spouse',
      phone: '+91 98401 99887',
      address: '14/2 Gandhi Road, T. Nagar, Chennai'
    },
    guarantor: {
      hasGuarantor: false,
      name: '',
      phone: '',
      idProof: '',
      address: ''
    },
    date: '25/08/2026',
    loanType: 'GOLD LOAN',
    repaymentSystem: 'Monthly interest only',
    area: 'T. Nagar Central',
    showroom: 'Main Branch - Counter 1',
    principal: 100000,
    interestRate: 2.0,
    bankMode: 'UPI',
    cashAmount: 0,
    bankAmount: 100000,
    deductAdvanceInterest: false,
    advanceDays: 0,
    advanceInterestAmount: 0,
    cardFee: 10,
    cardFeePaymentMode: 'Cash',
    items: [
      {
        id: 'item-1',
        item: 'Gold Chain with Pendant',
        qty: 1,
        purity: '22ct',
        grossWeight: 24.500,
        netWeight: 23.200
      },
      {
        id: 'item-2',
        item: 'Gold Bangles Pair',
        qty: 2,
        purity: '22ct',
        grossWeight: 16.800,
        netWeight: 16.200
      }
    ],
    totalGrossWeight: 41.300,
    totalNetWeight: 39.400,
    marketValue: 145000,
    ltv: 68.96,
    monthlyInterest: 2000,
    notes: 'Pledged for business working capital',
    photos: [],
    status: 'ACTIVE',
    disbursedAmount: 100000,
    outstandingPrincipal: 98500,
    accruedInterest: 0,
    renewalDate: '25/08/2027'
  },
  {
    id: 'L-02',
    receiptBillNo: 2,
    loanNo: 'GL-02',
    customerId: 'CUST-002',
    customerName: 'Rajan Sundaram',
    customerPhone: '+91 98840 98765',
    customerGender: 'Male',
    customerAge: 45,
    customerOccupation: 'Civil Contractor',
    customerEmail: 'rajan.s@example.com',
    customerCurrentAddress: '88 North Mada Street, Mylapore, Chennai - 600004',
    customerPermanentAddress: '88 North Mada Street, Mylapore, Chennai - 600004',
    date: '20/08/2026',
    loanType: 'GOLD LOAN',
    repaymentSystem: 'Monthly interest only',
    area: 'Mylapore',
    showroom: 'Main Branch - Counter 2',
    principal: 150000,
    interestRate: 2.0,
    bankMode: 'Split',
    cashAmount: 50000,
    bankAmount: 100000,
    deductAdvanceInterest: true,
    advanceDays: 30,
    advanceInterestAmount: 3000,
    cardFee: 10,
    cardFeePaymentMode: 'Cash',
    items: [
      {
        id: 'item-3',
        item: 'Gold Necklace & Earrings',
        qty: 1,
        purity: '22ct',
        grossWeight: 62.000,
        netWeight: 58.500
      }
    ],
    totalGrossWeight: 62.000,
    totalNetWeight: 58.500,
    marketValue: 215000,
    ltv: 69.76,
    monthlyInterest: 3000,
    notes: 'Advance interest deducted at disbursement',
    photos: [],
    status: 'ACTIVE',
    disbursedAmount: 147000,
    outstandingPrincipal: 150000,
    accruedInterest: 1500,
    renewalDate: '20/08/2027'
  },
  {
    id: 'L-03',
    receiptBillNo: 3,
    loanNo: 'GL-03',
    customerId: 'CUST-003',
    customerName: 'Kavitha Murugan',
    customerPhone: '+91 97910 54321',
    customerGender: 'Female',
    customerAge: 38,
    customerOccupation: 'School Teacher',
    customerEmail: 'kavitha.m@example.com',
    customerCurrentAddress: '22 Ring Road, Anna Nagar, Chennai - 600040',
    customerPermanentAddress: '22 Ring Road, Anna Nagar, Chennai - 600040',
    date: '12/08/2026',
    loanType: 'GOLD LOAN',
    repaymentSystem: 'Monthly interest only',
    area: 'Anna Nagar',
    showroom: 'Main Branch - Counter 1',
    principal: 85000,
    interestRate: 1.8,
    bankMode: 'Bank Transfer',
    cashAmount: 0,
    bankAmount: 85000,
    deductAdvanceInterest: false,
    advanceDays: 0,
    advanceInterestAmount: 0,
    cardFee: 10,
    cardFeePaymentMode: 'Cash',
    items: [
      {
        id: 'item-4',
        item: 'Gold Ring & Bracelet',
        qty: 2,
        purity: '22ct',
        grossWeight: 33.200,
        netWeight: 31.800
      }
    ],
    totalGrossWeight: 33.200,
    totalNetWeight: 31.800,
    marketValue: 120000,
    ltv: 70.83,
    monthlyInterest: 1530,
    notes: 'Safe deposit box A-12',
    photos: [],
    status: 'ACTIVE',
    disbursedAmount: 85000,
    outstandingPrincipal: 85000,
    accruedInterest: 765,
    renewalDate: '12/08/2027'
  }
];

export const initialReceipts: Receipt[] = [
  {
    id: 'RCPT-002',
    receiptNo: 2,
    loanId: 'L-01',
    loanNo: 'GL-01',
    customerId: 'CUST-001',
    customerName: 'thayba',
    kind: 'REPAYMENT',
    loanType: 'GOLD LOAN',
    amount: 1500,
    principalComponent: 1500,
    interestComponent: 0,
    paymentMode: 'Cash',
    date: '25/08/2026',
    notes: 'Part principal repayment'
  },
  {
    id: 'RCPT-001',
    receiptNo: 1,
    loanId: 'L-01',
    loanNo: 'GL-01',
    customerId: 'CUST-001',
    customerName: 'thayba',
    kind: 'NEW LOAN',
    loanType: 'GOLD LOAN',
    amount: 100000,
    principalComponent: 100000,
    interestComponent: 0,
    paymentMode: 'UPI',
    date: '25/08/2026',
    notes: 'Loan disbursement'
  },
  {
    id: 'RCPT-003',
    receiptNo: 3,
    loanId: 'L-02',
    loanNo: 'GL-02',
    customerId: 'CUST-002',
    customerName: 'Rajan Sundaram',
    kind: 'NEW LOAN',
    loanType: 'GOLD LOAN',
    amount: 150000,
    principalComponent: 150000,
    interestComponent: 0,
    paymentMode: 'UPI',
    date: '20/08/2026',
    notes: 'Loan disbursement'
  }
];

export const initialFixedDeposits: FixedDeposit[] = [
  {
    id: 'FD-001',
    fdNo: 'FD-01',
    customerId: 'CUST-001',
    depositorName: 'Thayba Begum',
    phone: '+91 98401 23456',
    idProofType: 'Aadhaar Card',
    idProofNumber: 'XXXX-XXXX-8921',
    address: '14/2 Gandhi Road, T. Nagar, Chennai',
    depositDate: '25-08-2026',
    maturityDate: '25-08-2027',
    principal: 200000,
    interestRatePA: 12.0,
    receivingMethod: 'Cash',
    monthlyPayout: 2000,
    status: 'ACTIVE'
  },
  {
    id: 'FD-002',
    fdNo: 'FD-02',
    customerId: 'CUST-004',
    depositorName: 'Arun Kumar',
    phone: '+91 94440 11223',
    idProofType: 'PAN Card',
    idProofNumber: 'ABCDE5678G',
    address: '5 Patel Street, Velachery, Chennai',
    depositDate: '10-08-2026',
    maturityDate: '10-08-2027',
    principal: 500000,
    interestRatePA: 12.5,
    receivingMethod: 'Bank',
    monthlyPayout: 5208,
    status: 'ACTIVE'
  }
];
