import admin from 'firebase-admin';
import dotenv from 'dotenv';

dotenv.config();

const projectId = process.env.FIREBASE_PROJECT_ID || 'otp-site-80c03';
const clientEmail = process.env.FIREBASE_CLIENT_EMAIL?.trim();
const rawPrivateKey = process.env.FIREBASE_PRIVATE_KEY?.trim();
const privateKey = rawPrivateKey ? rawPrivateKey.replace(/\\n/g, '\n') : undefined;

if (admin.apps.length === 0) {
  if (clientEmail && privateKey) {
    try {
      admin.initializeApp({
        credential: admin.credential.cert({
          projectId,
          clientEmail,
          privateKey,
        }),
        projectId,
      });
      console.log(`[FirebaseAdmin] Initialized with Service Account for project: ${projectId}`);
    } catch (certErr: any) {
      console.warn(`[FirebaseAdmin] Failed to initialize with cert credentials (${certErr.message}), falling back to Project ID config.`);
      admin.initializeApp({ projectId });
    }
  } else {
    admin.initializeApp({
      projectId,
    });
    console.log(`[FirebaseAdmin] Initialized for project: ${projectId} (Public x509 token verification enabled)`);
  }
}

export const firebaseAdmin = admin;
export const firebaseAuth = admin.auth();

export interface VerifiedFirebaseUser {
  uid: string;
  email: string;
  name?: string;
  picture?: string;
  emailVerified?: boolean;
}

/**
 * Verify a Firebase ID Token generated by Firebase Authentication on frontend (port 5174).
 * Uses public Google x509 cert validation for project kkv-gold-f9994.
 */
export const verifyFirebaseIdToken = async (idToken: string): Promise<VerifiedFirebaseUser | null> => {
  try {
    if (!idToken || typeof idToken !== 'string') {
      console.warn('[FirebaseAdmin] verifyFirebaseIdToken called with empty or non-string token');
      return null;
    }

    const cleanToken = idToken.trim();
    if (!cleanToken) {
      console.warn('[FirebaseAdmin] verifyFirebaseIdToken called with whitespace token');
      return null;
    }

    // Standard verifyIdToken without checkRevoked to ensure local public-cert verification
    const decodedToken = await admin.auth().verifyIdToken(cleanToken, false);

    if (!decodedToken || !decodedToken.uid) {
      console.warn('[FirebaseAdmin] verifyIdToken returned null or missing UID');
      return null;
    }

    const email = (decodedToken.email || '').toLowerCase().trim();

    console.log(`[FirebaseAdmin] Verified Firebase ID Token successfully (UID: ${decodedToken.uid.slice(0, 6)}..., Email: ${email})`);

    return {
      uid: decodedToken.uid,
      email: email || `${decodedToken.uid}@firebase.user`,
      name: decodedToken.name || (email ? email.split('@')[0] : 'Staff Member'),
      picture: decodedToken.picture,
      emailVerified: decodedToken.email_verified,
    };
  } catch (err: any) {
    console.warn('[FirebaseAdmin] Token verification failed:', err.code || err.message);
    return null;
  }
};
